# Generated by Django 2.2.27 on 2022-07-08 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_diamondcount_expensehistory_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diamonds', models.BigIntegerField()),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BuyMenu_platform', to='item.Platform')),
            ],
        ),
    ]
