# Generated by Django 2.2.27 on 2022-07-08 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_buymenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diamondcount',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='diamondcount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='expensehistory',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='expensehistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='BuyMenu',
        ),
        migrations.DeleteModel(
            name='DiamondCount',
        ),
        migrations.DeleteModel(
            name='ExpenseHistory',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
