# Generated by Django 2.2.27 on 2022-07-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePlayPurchaseHistoryTmp',
            fields=[
                ('purchaseToken', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('date_submited', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_submited')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buy_diamonds', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GooglePlayPurchaseHistoryTmp_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExpenseHistory',
        ),
    ]
