# Generated by Django 2.2.27 on 2022-06-19 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0002_auto_20220619_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouptopiccomment',
            name='topic',
        ),
        migrations.AddField(
            model_name='usercomment',
            name='submit_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserComment_submit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserComment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupTopic',
        ),
        migrations.DeleteModel(
            name='GroupTopicComment',
        ),
    ]
