# Generated by Django 2.2.27 on 2022-06-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_grouptopic_grouptopiccomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptopic',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Group'),
        ),
    ]
