# Generated by Django 2.2.27 on 2022-06-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20220619_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptopic',
            name='is_not_belong_viewable',
            field=models.BooleanField(default=False),
        ),
    ]
