# Generated by Django 2.2.27 on 2022-06-26 14:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_grouptopic_is_not_belong_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouptopiccomment',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined'),
        ),
        migrations.AddField(
            model_name='grouptopiccomment',
            name='date_submited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined'),
        ),
        migrations.AddField(
            model_name='grouptopiccomment',
            name='is_edit',
            field=models.BooleanField(default=False),
        ),
    ]
