# Generated by Django 2.2.27 on 2022-07-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0007_auto_20220626_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptopiccomment',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_edited'),
        ),
        migrations.AlterField(
            model_name='grouptopiccomment',
            name='date_submited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_submited'),
        ),
        migrations.CreateModel(
            name='GroupTopicCommentEvaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good', models.BooleanField()),
                ('group_topic_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupTopicCommentEvaluate_groupTopicComment', to='comment.GroupTopicComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupTopicCommentEvaluate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
