# Generated by Django 2.2.27 on 2022-07-04 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comment', '0008_auto_20220704_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommentEvaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_good', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCommentEvaluate_user', to=settings.AUTH_USER_MODEL)),
                ('user_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserCommentEvaluate_userComment', to='comment.UserComment')),
            ],
        ),
    ]
