# Generated by Django 2.2.27 on 2022-07-06 14:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_usercommentevaluate'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomment',
            name='date_edited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_edited'),
        ),
        migrations.AddField(
            model_name='usercomment',
            name='date_submited',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_submited'),
        ),
    ]
