# Generated by Django 2.2.27 on 2022-07-25 15:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RootBoxTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('common_prefix_key', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRootBoxState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key_usr', models.CharField(max_length=100)),
                ('hash_key_index', models.CharField(max_length=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRootBoxState_term', to='rootbox.RootBoxTerm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRootBoxState_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RootBoxItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=500)),
                ('permutation', models.IntegerField()),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rootbox.RootBoxTerm')),
            ],
        ),
    ]
