# Generated by Django 2.2.27 on 2022-07-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootboxitem',
            old_name='permutation',
            new_name='permutation_from',
        ),
        migrations.AddField(
            model_name='rootboxitem',
            name='permutation_to',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userrootboxstate',
            name='hash_key_index',
            field=models.IntegerField(default=0),
        ),
    ]
