# Generated by Django 2.2.27 on 2022-07-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rootbox', '0002_auto_20220730_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rootboxitem',
            old_name='permutation_from',
            new_name='permutation',
        ),
        migrations.RemoveField(
            model_name='rootboxitem',
            name='permutation_to',
        ),
    ]
