# Generated by Django 2.2.27 on 2022-08-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootbox', '0003_auto_20220731_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrootboxstate',
            name='index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
