# Generated by Django 2.2.27 on 2022-06-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220611_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='test@testmail.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
