# Generated by Django 2.2.27 on 2022-06-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220611_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroupinfo',
            name='group_join_waitconfirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='auto_belong_group',
            field=models.BooleanField(default=False),
        ),
    ]
