# Generated by Django 2.2.27 on 2022-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220612_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('hash_address', models.CharField(max_length=100)),
                ('valid_time', models.TimeField()),
                ('username', models.CharField(max_length=100)),
                ('tmp_password', models.CharField(max_length=50)),
            ],
        ),
    ]
