# Generated by Django 2.2.27 on 2022-06-15 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_mailinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_key', models.CharField(db_index=True, default='', max_length=200)),
                ('push_notification_token', models.CharField(max_length=100)),
                ('register_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
