# Generated by Django 2.2.27 on 2022-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220618_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsaver',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
