# Generated by Django 2.2.27 on 2022-06-19 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_processsaver_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComment',
        ),
    ]
