# Generated by Django 2.2.27 on 2022-07-08 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_usercomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_token', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_joined')),
                ('inviter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
