# Generated by Django 2.2.27 on 2022-07-24 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionCandidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('election_start_time', models.DateTimeField()),
                ('election_end_time', models.DateTimeField()),
                ('election_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionTitle')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionUserSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election_candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ElectionUserSubmit_election_candidate', to='election.ElectionCandidate')),
                ('election_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ElectionUserSubmit_election_unit', to='election.ElectionUnit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='electioncandidate',
            name='election_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ElectionCandidate_election_unit', to='election.ElectionUnit'),
        ),
    ]
