# Generated by Django 2.2.27 on 2022-07-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electiontitle',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
