# Generated by Django 2.2.27 on 2022-07-24 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_electiontitle_is_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionusersubmit',
            name='election_candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ElectionUserSubmit_election_candidate', to='election.ElectionCandidate'),
        ),
    ]
