# Generated by Django 2.2.27 on 2022-07-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_auto_20220724_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='electioncandidate',
            name='final_get_submits',
            field=models.BigIntegerField(default=0),
        ),
    ]
